### ISSUE TITLE
Homewizard kettle integration not working since HA 2025.6 release

### ISSUE THREAD

**Issue by gui017** [lesleyxyz/hass-homewizard-kettle#2]
Hello,
The integration does not work anymore (starting 2025.6 release) since it calls hass.config_entries.async_forward_entry_setup which is deprecated with this release.
Source : https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

When upgrading HASS to 2025.6, the integration does not load and I get an error message in the log telling the call to hass.config_entries.async_forward_entry_setup is unknown and proposing hass.config_entries.async_forward_entry_setups. (I can't paste the detailed log since I rolled back to 2025.5.3 since then).

As I'm not developper myself,  I don't have enough knowledge to try and patch  --> can you fix it ?

Thanks very much for the integration BTW 👍

**Comment by gui017** [comment]
I updated the integration to v0.7 while staying in HASS 2025.5.3.
Unfortunately, it fails :(

In the error list I get this : 

_Error setting up entry kettle/3c39e72ac18a for homewizard_kitchen_kettle
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewizard_kitchen_kettle/__init__.py", line 44, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2568, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 1 more time]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1151, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1076, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1250, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1282, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homewizard_kitchen_kettle/water_heater.py", line 3, in <module>
    from homeassistant.components.water_heater import (
    ...<3 lines>...
    )
ImportError: cannot import name 'SUPPORT_OPERATION_MODE' from 'homeassistant.components.water_heater' (/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py)_

**Comment by gui017** [comment]
0.8 works with HASS 2025.5.3 👍
I will update HASS to 2025.6 tonight and report the result here.
Thanks very much, you saved my wife tea routine 😊
